include ../configure.mk
include ../build.mk

SOURCES = isupport.c \
		message.c \
		nick.c \
		mode.c \
		client.c \
		hook.c \
		log.c
OBJECTS = ${SOURCES:.c=.o}

compile:
	@${COMPILE_OBJECTS}
clean:
	@${CLEAN_OBJECTS}
